# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  schedule:
    - cron: '0 3 * * *' # Run every Argentinian midnight

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Pages
        uses: actions/configure-pages@v1
      - name: Create build
        run: |
          mkdir -p build build/hn
          cp index.html CNAME build/
      - name: Snapshot news sites at midnight
        if: ${{ github.event_name == 'schedule' }}
        run: |
          ruby ./crawl/hacker-news.rb
          cp hacker-news.html build/hn/index.html
      - name: Fetch existing news sites snapshots on other builds
        if: ${{ github.event_name != 'schedule' }}
        run: |
          wget https://deja.de.hueve.ar/hn/index.html -O build/hn/index.html
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: './build'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
